# Generated by Django 4.0.4 on 2022-09-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needtoreview',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, related_name='review_cards', to='main.card'),
        ),
    ]
