# Generated by Django 4.0.4 on 2022-05-30 12:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_unknowcards_needtoreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='backcard',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
