# Generated by Django 4.0.4 on 2022-09-28 21:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_needtoreview_cards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeedToReview',
            new_name='NeedToRemember',
        ),
    ]
