# Generated by Django 4.0.4 on 2022-05-31 19:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_card_backcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='backcard',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
