# Generated by Django 4.0.4 on 2022-06-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_card_backcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnknowCards',
        ),
    ]
