# Generated by Django 4.0.4 on 2022-06-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_needtoreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='need_to_review',
            field=models.ManyToManyField(related_name='need_to_review', to='main.needtoreview'),
        ),
    ]
