# Generated by Django 4.0.4 on 2022-06-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_card_need_to_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='need_to_review',
        ),
    ]
